version: "3.8"

services:
  postgres:
    container_name: postgres_easymemo1
    hostname: postgres
    image: postgres:13.5
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - ./api/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-pgadmin

  pgadmin:
    container_name: pgadmin_easymemo
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./api/.env
    volumes:
      - ./api/pgadmin-data:/var/lib/pgadmin-docker
    ports:
      - 6060:80
    networks:
      - postgres-pgadmin

  # api:
  #   image: nestjs-api
  #   hostname: api
  #   build: ./api
  #   env_file:
  #     - ./api/.env
  #   ports:
  #     - 8001:8001
  #   networks:
  #     - postgres-pgadmin
  #
  # easymemo-front:
  #   container_name: easymemo-react
  #   restart: always
  #   build: ./frontend

networks:
  postgres-pgadmin:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  api:
