name: Deploy buy runner

on:
  push:
    branches: ["master"]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          clean: false
  prepare-environment:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f
  deploy-docker-compose:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: docker-compose
        run: docker-compose up -d
  # deploy-frontend:
  #   needs: checkout
  #   runs-on: self-hosted
  #   steps:
  #     - name: deploy-frontend
  #       run: cd frontend && npm i && npm run build
